# forge/agents/coder.py
from pathlib import Path
from .base import BaseAgent
from ..utils import strip_code_fences
from ..prompts import PromptLibrary

class CoderAgent(BaseAgent):
    PASSTHROUGH = ("ir.model.access.csv",)

    def __init__(self, llm_client, config, module_meta: dict = None, knowledge_store = None):
        self.llm = llm_client
        self.config = config
        self.module_meta = module_meta or {}
        self.knowledge_store = knowledge_store
        self.generated: dict = {}

    def _ref_ctx(self, target_filepath: str = "") -> str:
        """Build context from previously generated files with field summaries."""
        if not self.generated:
            return ""
            
        rag_context = ""
        if self.knowledge_store:
            rag_context = self.knowledge_store.retrieve_context(target_filepath)

        ctx = (
            "[TEAM SHARED MEMORY — files already generated by your teammates]\n"
            "You MUST be fully consistent with these. Reference their field names, model names, "
            "and XML IDs exactly as declared below. DO NOT redefine models or fields already defined.\n\n"
        )
        if rag_context:
            ctx += rag_context + "\n\n"
        
        models_summary = []
        xml_summary = []
        
        for path, code in self.generated.items():
            # For Python model files, extract field names for quick reference
            if path.endswith(".py") and "models/" in path and not path.endswith("__init__.py"):
                fields = self._extract_fields(code)
                model_name = self._extract_model_name(code)
                if model_name:
                    models_summary.append(f"Model '{model_name}' ({path}): Fields = [{', '.join(fields)}]")
                    ctx += f"--- MODEL: {model_name} ({path}) ---\n"
                    ctx += f"Declared Fields: {', '.join(fields)}\n\n"
                else:
                    snippet = code[:1500] + "\n...[truncated]" if len(code) > 1500 else code
                    ctx += f"--- TEAMMATE FILE: {path} ---\n{snippet}\n\n"
            else:
                if path.endswith(".xml"):
                    xml_ids = self._extract_xml_ids(code)
                    if xml_ids:
                        xml_summary.append(f"File '{path}': XML IDs = [{', '.join(xml_ids)}]")
                        ctx += f"--- XML FILE: {path} ---\nDeclared XML IDs: {', '.join(xml_ids)}\n\n"
                    else:
                        snippet = code[:1500] + "\n...[truncated]" if len(code) > 1500 else code
                        ctx += f"--- TEAMMATE FILE: {path} ---\n{snippet}\n\n"
                else:
                    snippet = code[:1000] + "\n...[truncated]" if len(code) > 1000 else code
                    ctx += f"--- TEAMMATE FILE: {path} ---\n{snippet}\n\n"
        
        ctx += "[SUMMARY OF DECLARED ARCHITECTURE]\n"
        if models_summary:
            ctx += "Models & Fields Available (Use ONLY these declared field names in views):\n" + "\n".join(f"  • {m}" for m in models_summary) + "\n\n"
        if xml_summary:
            ctx += "Declared Actions & XML IDs (Reference these exact IDs in menus & actions):\n" + "\n".join(f"  • {x}" for x in xml_summary) + "\n\n"
        ctx += "[PRODUCTION DESIGN DIRECTIVES]\n"
        ctx += "1. Parent-Child Relations: Connect One2many and Many2one fields cleanly with matching inverse_name.\n"
        ctx += "2. Form Views: Include Smart Stat Buttons inside <div class=\"oe_button_box\">, notebook pages for One2many lines, and <chatter/>.\n"
        ctx += "3. List Views: Use Odoo 18 <list> tag with status decorations (decoration-success, decoration-info).\n"
        ctx += "4. Menus: Map menu items to declared window actions in logical sequence.\n"
        ctx += "[END TEAM SHARED MEMORY]\n\n"
        return ctx

    def _extract_xml_ids(self, code: str) -> list:
        """Extract record, menuitem, and template IDs from an XML file."""
        import re
        xml_ids = []
        for match in re.finditer(r'id=["\']([^"\']+)["\']', code):
            xml_ids.append(match.group(1))
        return xml_ids[:20]  # Cap at 20 IDs for space

    def _extract_fields(self, code: str) -> list:
        """Extract field names from a Python model file."""
        import re
        fields = []
        # Match field definitions: field_name = fields.xxx(...)
        for match in re.finditer(r'^\s+(\w+)\s*=\s*fields\.\w+\(', code, re.MULTILINE):
            fields.append(match.group(1))
        return fields

    def _extract_model_name(self, code: str) -> str:
        """Extract _name from a Python model file."""
        import re
        match = re.search(r"_name\s*=\s*['\"]([^'\"]+)['\"]", code)
        return match.group(1) if match else ""

    def generate(self, bf, bp_summary: str, feedback: str = "") -> str:
        # Build file list context from all generated files
        file_list = "\n".join(f"- {fp}" for fp in self.generated.keys())
        
        # For init files, provide exact import list
        if bf.filepath.endswith("__init__.py"):
            # Get list of model files that exist
            model_files = [fp for fp in self.generated.keys() 
                          if fp.startswith("models/") and fp.endswith(".py") 
                          and not fp.endswith("__init__.py")]
            model_imports = "\n".join(f"from . import {Path(fp).stem}" for fp in model_files)
            
            init_prompt = (
                f"Generate an __init__.py file.\n"
                f"FILE PATH: {bf.filepath}\n\n"
                f"FILES IN THIS MODULE:\n{file_list}\n\n"
                f"IMPORTS TO USE (copy exactly, do not add or change):\n{model_imports}\n\n"
                f"RULES:\n"
                f"- Output ONLY the import lines shown above\n"
                f"- Do NOT add any other imports\n"
                f"- Do NOT add comments or docstrings\n"
            )
            return strip_code_fences(self.llm.call(
                PromptLibrary.coder_system(bf.filepath, self.module_meta),
                init_prompt,
                self.config.resolve_model("coder"),
                temperature=0.05,
            ))
        
        # CSV files: generate proper CSV format, not markdown
        if bf.filepath.endswith(".csv"):
            csv_prompt = (
                f"Generate a proper CSV file for ir.model.access.csv.\n"
                f"FILE PATH: {bf.filepath}\n"
                f"DESCRIPTION: {bf.description}\n"
                f"MODULE: {self.module_meta.get('technical_name', 'unknown')}\n\n"
                f"FILES IN THIS MODULE:\n{file_list}\n\n"
                f"REQUIRED FORMAT:\n"
                f"id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink\n\n"
                f"RULES:\n"
                f"- One row per model per security group\n"
                f"- model_id:id uses model_ prefix: e.g., model_my_model\n"
                f"- Group IDs reference XML IDs defined in security.xml\n"
                f"- NO markdown, NO pipe delimiters, NO headers — just comma-separated values\n"
                f"- Every model in the module MUST have at least 2 rows (user + manager)\n"
                f"- ONLY reference models that exist in the FILES IN THIS MODULE list above\n"
            )
            return strip_code_fences(self.llm.call(
                PromptLibrary.coder_system(bf.filepath, self.module_meta),
                csv_prompt,
                self.config.resolve_model("coder"),
                temperature=0.05,
            ))

        user_prompt = (
            f"MODULE BLUEPRINT:\n{bp_summary}\n\n{self._ref_ctx(bf.filepath)}\n"
            f"FILES IN THIS MODULE (you MUST use these exact paths):\n{file_list}\n\n"
            f"Generate code for EXACTLY ONE file.\nFILE PATH: {bf.filepath}\n"
            f"DESCRIPTION: {bf.description}\n"
            + (f"\nTECHNICAL SPEC:\n{bf.spec}\n" if bf.spec else "")
            + (f"\n[REVISION REQUIRED — address all critic feedback]: {feedback}\n" if feedback else "")
        )
        skill_query = f"Odoo 18 {Path(bf.filepath).suffix.strip('.')} {bf.description} {bf.filepath}"
        return strip_code_fences(self.llm.call(
            PromptLibrary.coder_system(bf.filepath, self.module_meta),
            user_prompt, self.config.resolve_model("coder"), temperature=0.1,
            skill_query=skill_query))

    def auto_fix(self, bf, error_msg: str) -> str:
        """Fix code based on specific issues from critic."""
        # Filter issues to only those relevant to this file type
        file_ext = Path(bf.filepath).suffix
        filtered_issues = []

        for line in error_msg.split("\n"):
            line = line.strip()
            if not line:
                continue
            # Skip XML issues when fixing Python files
            if file_ext == ".py" and any(kw in line.lower() for kw in ["<tree>", "<list>", "xml", "view tag", "view_mode"]):
                continue
            # Skip Python issues when fixing XML files
            if file_ext == ".xml" and any(kw in line.lower() for kw in ["field:", "method:", "_name", "_description", "_order", "import"]):
                continue
            # Skip issues that don't match file type
            if file_ext == ".py" and "missing_row" in line.lower():
                continue
            if file_ext == ".csv" and any(kw in line.lower() for kw in ["field", "method", "view"]):
                continue
            filtered_issues.append(line)

        if not filtered_issues:
            # No relevant issues — return original content
            return bf.content

        filtered_msg = "\n".join(filtered_issues)
        user_prompt = (
            f"FILE PATH: {bf.filepath}\n\n"
            f"ISSUES TO FIX:\n{filtered_msg}\n\n"
            f"CURRENT CODE:\n{bf.content}\n\n"
            "Fix ONLY the issues above that apply to this file type. "
            "Output the COMPLETE corrected file."
        )
        return strip_code_fences(self.llm.call(
            PromptLibrary.auto_fix_system(),
            user_prompt,
            self.config.resolve_model("coder"), temperature=0.05))
